---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/static-golang

inputs:
- name: semver-resource
  path: gopath/src/github.com/concourse/semver-resource

outputs:
- name: built-resource

params:
  SEMVER_TESTING_ACCESS_KEY_ID:
  SEMVER_TESTING_SECRET_ACCESS_KEY:
  SEMVER_TESTING_BUCKET:
  SEMVER_TESTING_REGION:

run:
  path: gopath/src/github.com/concourse/semver-resource/scripts/ci
